"""add more col in pitches table

Revision ID: 5d18097ab3dc
Revises: b6018483a52a
Create Date: 2020-05-05 22:16:56.219658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d18097ab3dc'
down_revision = 'b6018483a52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_pitches_description'), 'pitches', ['description'], unique=False)
    op.create_foreign_key(None, 'pitches', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_index(op.f('ix_pitches_description'), table_name='pitches')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'owner_id')
    op.drop_column('pitches', 'description')
    # ### end Alembic commands ###
