"""remove owner_id col

Revision ID: b6018483a52a
Revises: 7a4877d378da
Create Date: 2020-05-05 21:41:34.145536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6018483a52a'
down_revision = '7a4877d378da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_owner_id_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('pitches_owner_id_fkey', 'pitches', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
